version: "3"

services:
  # zoo:
  #   image: cfei/zookeeper:2.0.0-beta
  #   container_name: zookeeper
  #   restart: always
  #   ports:
  #     - 2181:2181
  #     - 2888:2888
  #     - 3888:3888
  #   environment:
  #     ZOO_ID: 1
  #     ZOO_PORT: 2181

  acl-manager:
    image: omvk97/acl-manager
    container_name: acl-manager
    ports:
      - 9000:9000
    environment:
      AUTHORIZER_ZOOKEEPER_CONNECT: 134.209.88.200:2181
      ACL_API_PORT: 9000
      ACL_API_KEY: password
      ACL_KERBEROS_API_URL: "http://134.209.198.150:3000/get-keytab"
      ACL_KERBEROS_API_ZOOKEEPER_USERNAME: zookeeper/134.209.88.200
      ACL_KERBEROS_API_ZOOKEEPER_PASSWORD: zookeeperPassword
      ACL_KERBEROS_REALM: CFEI.SECURE
      ACL_KERBEROS_PUBLIC_URL: 134.209.198.150
